### PR TITLE
Added Japanese translation

### PR DESCRIPTION
**Pull request by kuragehimekurara1**

### CODE REVIEW

**Comment by eritpchy** [comment]
感谢贡献, 但其实还有挺多的, src/main/java/com/surcumference/fingerprint/Lang.java, 以及代码内对ViewUtils.findViewByText的引用

**Comment by kuragehimekurara1** [comment]
I would love to translate that too!
Should I add it to strings.xml in the values-ja folder?
Please let me know if there is another way!

**Comment by kuragehimekurara1** [comment]
I would love to translate that too!
Should I add it to strings.xml in the values-ja folder?
Please let me know if there is another way!

**Comment by eritpchy** [comment]
This four line in values-ja/strings.xml should be fine.
In the Lang.java, format ex: tr("指纹支付", "指纹支付", "Fingerprint Pay", "Japanese text");
For ViewUtils.findViewByText ref, If target app has Japanese translation(for example: Wechat), you should copy these text from app paste into ViewUtils.findViewByText(last argument), If it's too much trouble, you can skip this and just translate Lang.java.

Thanks.

**Pull request closed without merging**
